const MAX_TOKENS_AMOUNT_PER_USER = 20;

const EMAIL_TO_CONFIRM_EXPIRES_AFTER_S = 259200;
const SHORT_TERM_EMAIL_EXPIRES_AFTER_S = 60;

module.exports = {
    MAX_TOKENS_AMOUNT_PER_USER,
    EMAIL_TO_CONFIRM_EXPIRES_AFTER_S,
    SHORT_TERM_EMAIL_EXPIRES_AFTER_S
};